### ISSUE TITLE
Mac library linking

### ISSUE THREAD

**Issue by Dreksh** [HPCE/hpce-2015-cw3#1]
I got this error when trying to run bin/test_tbb on a mac:

dyld: Library not loaded: libtbb.dylib
  Referenced from: /directory/to/repository/bin/test_tbb
  Reason: image not found
Trace/BPT trap:5

It turns out that the binaries are not linking to the libtbb correctly (I did not store them in /usr/lib/), and assumes that they are in the same directory as the executable. My fix for this was to append a line of code in the makefile after each 'bin/executable' target to change the linking
```
$(foreach var, $(shell otool -L $@ | grep -v $@ | sed "s/   //" | sed "s/(.*)//" | grep -v "/"), install_name_tool -change $(var) $(TBB_LIB_DIR)$(var) $@ ;)
```
Is there a better way of fixing this where the linking happens when creating the binary rather than changing it afterwards?

**Comment by Dreksh** [comment]
http://qin.laya.com/tech_coding_help/dylib_linking.html
I might be working with an outdated version of tbb

**Comment by m8pple** [comment]
I'm afraid on the Mac side of things I don't really have much knowledge,
so this might be a more a group effort. Last year someone contributed
the script: https://github.com/HPCE/hpce-2015-cw3/blob/master/osx_setup.sh

**Comment by aaronsheah** [comment]
on Mac OSX 10.11

before running ```bin/test_tbb```, I wrote the following :
```
export DYLD_LIBRARY_PATH=<insert path of lib of tbb>
```

and it worked for me

**Comment by Dreksh** [comment]
yup, DYLD_LIBRARY_PATH is a nice way of doing this
