### ISSUE TITLE
Unable to build tbb on cygwin

### ISSUE THREAD

**Issue by emadkhan2k** [HPCE/hpce-2015-cw3#2]
I have followed your instructions on the making of tbb on cygwin32:
>wget http://cas.ee.ic.ac.uk/people/dt10/teaching/2015/hpce/cw3/tbb42_20140601oss_src_cygwin.tgz
>tar -xf tbb42_20140601oss_src_cygwin.tgz
>cd tbb42_20140601oss
>make -j 4 # OMG, parallelism!

When I run the make command I get the following error message:
>Created ./build/cygwin_ia32_gcc_cc4.9.3_newlib_release and ..._debug directories
>make -C "./build/cygwin_ia32_gcc_cc4.9.3_newlib_debug"  -r -f ../../build/Makefile.tbb cfg=debug
>make[1]: Entering directory '/cygdrive/c/Users/Emad/Desktop/hpce-2015-cw3/tbb42_20140601oss/build/cygwin_ia32_gcc_cc4.9.3_newlib_debug'
>../../build/Makefile.tbb:39: CONFIG: cfg=debug arch=ia32 compiler=gcc target=cygwin runtime=cc4.9.3_newlib
>g++ -std=gnu++11 -D_TBB_CPP0X -o concurrent_queue.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor    -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_queue.cpp
>In file included from ../../src/tbb/itt_notify.h:46:0,
>                 from ../../src/tbb/concurrent_queue.cpp:36:
>../../src/tbb/tools_api/ittnotify.h:185:26: error: '__forceinline' does not name a type
> #define INLINE           __forceinline
>                          ^
>../../src/tbb/tools_api/ittnotify.h:1497:1: note: in expansion of macro 'INLINE'
> INLINE __itt_id ITTAPI __itt_id_make(void* addr, unsigned long long extra) INLINE_ATTRIBUTE;
> ^
>../../src/tbb/tools_api/ittnotify.h:185:26: error: '__forceinline' does not name a type
> #define INLINE           __forceinline
>                          ^
>../../src/tbb/tools_api/ittnotify.h:1498:1: note: in expansion of macro 'INLINE'
> INLINE __itt_id ITTAPI __itt_id_make(void* addr, unsigned long long extra)
> ^
>../../build/common_rules.inc:85: recipe for target 'concurrent_queue.o' failed
>make[1]: *** [concurrent_queue.o] Error 1
>make[1]: Leaving directory '/cygdrive/c/Users/Emad/Desktop/hpce-2015-cw3/tbb42_20140601oss/build/cygwin_ia32_gcc_cc4.9.3_newlib_debug'
>Makefile:40: recipe for target 'tbb' failed
>make: *** [tbb] Error 2

I am running cygwin32 on WIndows 10

**Comment by m8pple** [comment]
My cygwin/g++ config looks identical to yours, so it might be that windows 10 is somehow
involved (not sure how though). It works for me on Vista and Windows 7, which is all I
have.

The code-path it is following (in itt_notify.h) is:

    #if ITT_PLATFORM==ITT_PLATFORM_WIN
    /* use __forceinline (VC++ specific) */
    #define INLINE           __forceinline

So it looks like it is following the code-path for visual studio.

Further up the file there is:

    #ifndef ITT_PLATFORM
    #  if ITT_OS==ITT_OS_WIN
    #    define ITT_PLATFORM ITT_PLATFORM_WIN
    #  else
    #    define ITT_PLATFORM ITT_PLATFORM_POSIX
    #  endif /* _WIN32 */
    #endif /* ITT_PLATFORM */

That then gets set further up, but I can't see why it would follow a different path.

Could you try (none of these are true solutions, just trying to diagnose):

## TBB build info

Paste the contents of `make info` from the TBB dir.

e.g. I get:

    $ make info
    OS: cygwin
    arch=ia32
    compiler=gcc
    runtime=cc4.9.3_newlib
    tbb_build_prefix=cygwin_ia32_gcc_cc4.9.3_newlib

## Force the definition of __forceinline to an empty string

Try specifying a null value for __forceinline:

    make CXXFLAGS=-D__forceinline=

This may just cause errors elsewhere, but it would be good to know.

## Force the ITT platform and OS

It may be possible to force it back to posix, by doing:

     make CXXFLAGS+=-DITT_PLATFORM=2 CXXFLAGS+=-DITT_OS=2

Code 2 means posix for the ITT header, so it may work.

**Comment by emadkhan2k** [comment]
I have tried what you have suggested however it still doesn't work. 
Our make info seems to be identical
>$ make info
>OS: cygwin
>arch=ia32
>compiler=gcc
>runtime=cc4.9.3_newlib
>tbb_build_prefix=cygwin_ia32_gcc_cc4.9.3_newlib

Forcing the definition of __forceinline to an empty string:
>$ make CXXFLAGS=-D__forceinline=
>Created ./build/cygwin_ia32_gcc_cc4.9.3_newlib_release and ..._debug directories
>make -C "./build/cygwin_ia32_gcc_cc4.9.3_newlib_debug"  -r -f ../../build/Makefile.tbb cfg=debug
>make[1]: Entering directory '/cygdrive/c/Users/Emad/Desktop/hpce-2015-cw3/tbb42_20140601oss/build/cygwin_ia32_gcc_cc4.9.3_newlib_debug'
>../../build/Makefile.tbb:39: CONFIG: cfg=debug arch=ia32 compiler=gcc target=cygwin runtime=cc4.9.3_newlib
>g++ -std=gnu++11 -D_TBB_CPP0X -o concurrent_queue.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -D__forceinline=   -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_queue.cpp
>g++ -std=gnu++11 -D_TBB_CPP0X -o concurrent_vector.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -D__forceinline=   -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_vector.cpp
>g++ -std=gnu++11 -D_TBB_CPP0X -o dynamic_link.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -D__forceinline=   -I../../src -I../../src/rml/include -I../../include ../../src/tbb/dynamic_link.cpp
>../../src/tbb/dynamic_link.cpp: In function 'void tbb::internal::init_ap_data()':
>../../src/tbb/dynamic_link.cpp:267:13: error: 'GetModuleHandleEx' was not declared in this scope
>             );
>             ^
>../../src/tbb/dynamic_link.cpp: In function 'HINSTANCE__* tbb::internal::global_symbols_link(const char*, const tbb::internal::dynamic_link_descriptor*, std::size_t)':
>../../src/tbb/dynamic_link.cpp:465:61: error: 'GetModuleHandleEx' was not declared in this scope
>         if ( GetModuleHandleEx( 0, library, &library_handle ) ) {
>                                                             ^
>../../build/common_rules.inc:85: recipe for target 'dynamic_link.o' failed
>make[1]: *** [dynamic_link.o] Error 1
>make[1]: Leaving directory '/cygdrive/c/Users/Emad/Desktop/hpce-2015-cw3/tbb42_20140601oss/build/cygwin_ia32_gcc_cc4.9.3_newlib_debug'
>Makefile:40: recipe for target 'tbb' failed
>make: *** [tbb] Error 2

Forcing the ITT platform and OS
>$  make CXXFLAGS+=-DITT_PLATFORM=2 CXXFLAGS+=-DITT_OS=2
>Created ./build/cygwin_ia32_gcc_cc4.9.3_newlib_release and ..._debug directories
>make -C "./build/cygwin_ia32_gcc_cc4.9.3_newlib_debug"  -r -f ../../build/Makefile.tbb cfg=debug
>make[1]: Entering directory '/cygdrive/c/Users/Emad/Desktop/hpce-2015-cw3/tbb42_20140601oss/build/cygwin_ia32_gcc_cc4.9.3_newlib_debug'
>../../build/Makefile.tbb:39: CONFIG: cfg=debug arch=ia32 compiler=gcc target=cygwin runtime=cc4.9.3_newlib
>g++ -std=gnu++11 -D_TBB_CPP0X -o concurrent_hash_map.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -DITT_PLATFORM=2 -DITT_OS=2   -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_hash_map.cpp
>g++ -std=gnu++11 -D_TBB_CPP0X -o concurrent_queue.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -DITT_PLATFORM=2 -DITT_OS=2   -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_queue.cpp
>g++ -std=gnu++11 -D_TBB_CPP0X -o concurrent_vector.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -DITT_PLATFORM=2 -DITT_OS=2   -I../../src -I../../src/rml/include -I../../include ../../src/tbb/concurrent_vector.cpp
>g++ -std=gnu++11 -D_TBB_CPP0X -o dynamic_link.o -c -MMD -DTBB_USE_DEBUG -DDO_ITT_NOTIFY -g -O0 -DUSE_PTHREAD -m32 -march=pentium4 -mrtm  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -DITT_PLATFORM=2 -DITT_OS=2   -I../../src -I../../src/rml/include -I../../include ../../src/tbb/dynamic_link.cpp
>../../src/tbb/dynamic_link.cpp: In function 'void tbb::internal::init_ap_data()':
>../../src/tbb/dynamic_link.cpp:267:13: error: 'GetModuleHandleEx' was not declared in this scope
>             );
>             ^
>../../src/tbb/dynamic_link.cpp: In function 'HINSTANCE__* tbb::internal::global_symbols_link(const char*, const tbb::internal::dynamic_link_descriptor*, std::size_t)':
>../../src/tbb/dynamic_link.cpp:465:61: error: 'GetModuleHandleEx' was not declared in this scope
>         if ( GetModuleHandleEx( 0, library, &library_handle ) ) {
>                                                             ^
>../../build/common_rules.inc:85: recipe for target 'dynamic_link.o' failed
>make[1]: *** [dynamic_link.o] Error 1
>make[1]: Leaving directory '/cygdrive/c/Users/Emad/Desktop/hpce-2015-cw3/tbb42_20140601oss/build/cygwin_ia32_gcc_cc4.9.3_newlib_debug'
>Makefile:40: recipe for target 'tbb' failed
>make: *** [tbb] Error 2

**Comment by m8pple** [comment]
Thanks for that - it looks like quite a deep problem, as I'm still
not sure what it is about the environment that it is managing
to detect.

Am I right that you said you'd switched to linux?

**Comment by emadkhan2k** [comment]
No problem, yes I moved to Linux. Thanks for your help.

**Comment by raweed** [comment]
If I may add to this, this may be a issue with your computer rather than the file as I have successfully been able to get, -tar and make tbb on cygwin on 2 different machines, both of which are using windows 10. The only difference is both are on cygwin64 rather than cygwin32

>OS: cygwin
>arch=intel64
>compiler=gcc
>runtime=cc4.9.3_newlib
>tbb_build_prefix=cygwin_intel64_gcc_cc4.9.3_newlib

**Comment by raweed** [comment]
To add to this, just tried on cygwin32, maybe its a issue with your laptop as it seems to work for me, was able to follow instructions without issue and am able to run 
>bin/test_tbb

also running windows 10

>OS: cygwin
arch=ia32
compiler=gcc
runtime=cc4.9.3_newlib
tbb_build_prefix=cygwin_ia32_gcc_cc4.9.3_newlib

**Comment by m8pple** [comment]
I think I'll close this, as it doesn't seem something that is easily debugable, or on anyone's critical path.
