### ISSUE TITLE
Errors Building Clean From Make

### ISSUE THREAD

**Issue by jake2184** [HPCE/hpce-2015-cw3#3]
When I first built (make all), I was met by a couple of errors:
invalid_argument is not a member of std
clock_gettime is not defined

These were solved by:
adding < stdexcept > to fourier_transform.cpp
adding -lrt to LDLIBS in the makefile

This was on Ubuntu 12.04 with a freshly installed g++ 4.7.

**Comment by anferbui** [comment]
What did you add to fourier_transform.cpp? I have the same problem

**Comment by jake2184** [comment]
The header stdexcept. For some reason adding the < symbols hid it in my post.

**Comment by anferbui** [comment]
Thanks! This worked for me too

**Comment by m8pple** [comment]
Thanks @jake2184  - not sure how the missing `-lrt` was passing on my ubuntu install.
Ah, "LIBS" in my login script. This is why I should test as a different user.

I'll put them into the master version.
