### ISSUE TITLE
Wrong Fourier Transform Runs

### ISSUE THREAD

**Issue by rbhadti94** [HPCE/hpce-2015-cw3#5]
When running the commands:

```bin/test_fourier_transform hpce.LOGIN.direct_fourier_transform_parfor```
and

```bin/test_fourier_transform hpce.LOGIN.direct_fourier_transform_chunked```

I always get the same result of:

``` hpce.LOGIN.direct_fourier_transform_chunked: X/Y Passed```

for both commands.

It appears that only the chunked version will run even if I call the parfor version. 

i.e. It doesn't allow me to run the parfor version after I have registered the chunked version. I have made sure that the ```name()``` function returns the correct names and have also made sure that the correct functions are registered in the factory.

**Comment by m8pple** [comment]
Things to try:

- If you run just `bin/test_fourier_transform` with no arguments, does it list both of
  your implementations?

- If you comment out the chunked registration in `fourier_transform::RegisterDefaultFactories`,
  does it revert to the parfor version?

- If you start it in a debugger, and step through the process from main, all the way
   through the factories, at what point does it _not_ enter the parfor version.

**Comment by rbhadti94** [comment]
I have traced it down to the make file. 

If I place 

```src/LOGIN/direct_fourier_transform_parfor.o``` before ```src/LOGIN/direct_fourier_transform_chunked.o```, in the make file it will be the parfor version that runs. 

So apparently the order in which they are listed in ```FOURIER_IMPLEMENTATION_OBJS``` affects which one is called.

**Comment by m8pple** [comment]
That sounds like you have two symbols (functions)
with the same name, so the order in which they are
linked will determine which one gets called.

Check very carefully that your factory functions
in the parfor and chunked source files actually
have the correct names, and that there is only
one factory function in each source file.

Have you tried stepping through the source code
in a debugger (e.g. eclipse or GDB) to check which
direction each code path takes?

You may wish to modify the makefile to add `-g` to
CPPFLAGS, and remove `-O3` to make debugging easier.

Another option would be to put:

     std::cerr<<"In file "<<__FILE__<<", line "<<__LINE__<<"\n";

in your factory function. That way you can tell when
the program runs which factory function it is executing.

Actually, assuming you're using c++11, you can also use
`__func__` which will say what function is executing:

     std::cerr<<"In file "<<__FILE__<<", function "<<__func__
            << "line "<<__LINE__<<"\n";


David Thomas

**Comment by rbhadti94** [comment]
I have now cloned the original repository to a different location on my computer and gone through the steps once again. 

In my factory I have 
```namespace LOGIN{ ```
        ```std::shared_ptr<fourier_transform> Create_direct_fourier_transform_parfor();```
	```std::shared_ptr<fourier_transform> Create_direct_fourier_transform_chunked();```
``` } ```
and
```RegisterTransformFactory("hpce.rb2312.direct_fourier_transform_parfor", hpce::rb2312::Create_direct_fourier_transform_parfor);```

```RegisterTransformFactory("hpce.rb2312.direct_fourier_transform_chunked", hpce::rb2312::Create_direct_fourier_transform_chunked);```

At the end of my functions I have made sure that both functions return the correct name and also made sure that it says ```std::shared_ptr<fourier_transform>Create_direct_fourier_transform_TYPE()``` where TYPE is either parfor or chunked depending on the file.  

The name of the transform required being passed to ```fourier_transform::CreateTransform``` is also correct. I have checked this by using your above ```std::cerr``` statement to check the argument ```string &name```. 

I am currently setting up eclipse so I can use the debugger. However to me it seems like something is going wrong when the name-factory pairing is being setup in the map.

**Comment by rbhadti94** [comment]
After going through the debugger I found that the line ```acc<<"testDCTransform("<<pTransform->name()<<","<<n<<")";``` in ```test_fourier_transform.cpp``` returns the wrong name. But I still don't know where this problem is exactly occuring.

**Comment by m8pple** [comment]
I couldn't work out what could be going wrong from the description, so cheated and
looked inside your repo.

In `direct_fourier_transform_chunked.cpp` you have:

    namespace hpce
    {	
	//Encapsulated in user login.
	namespace LOGIN
	{
		class direct_fourier_transform
			: public fourier_transform
		{
		protected:

While in `direct_fourier_transform_parfor.cpp` you've got:

    namespace hpce
    {	
	//Encapsulated in user login.
	namespace LOGIN
	{
		class direct_fourier_transform
			: public fourier_transform

So in two different files you've defined the class `hpce::LOGIN::direct_fourier_transform`,
which means there are two different definitions for the same symbol.

So while you've got two different factory functions, they both instantiate
the same class. Which class that is will depends on which object file
comes first.

**Comment by rbhadti94** [comment]
Yes! Thanks very much this seems to be something I overlooked.
