### ISSUE TITLE
Suddenly unable to locate include/fourier_transform.hpp (Ubuntu)

### ISSUE THREAD

**Issue by mattdouthwaite** [HPCE/hpce-2015-cw3#6]
I am working on Ubuntu and got this error when I first tried to make all from the hpce-2015-cw3 folder. I used "export LD_LIBRARY_PATH=/absolute/path/to/include/dir" to add the absolute path to the include directory for the compiler and the problem went away. I was able to run both test_fourier_transform and time_fourier_transform.

However after creating a copy of the direct_fourier_transform in a subfolder in src (src/md2610/) and creating the new class and renaming, I tried to build the object file to put in the makefile as instructed. When I make this new cpp file I get the error:

md2610@doc-md2610:~/homedir/GitHub/hpce-2015-cw3/src$ make md2610/direct_fourier_transform_parfor
g++     md2610/direct_fourier_transform_parfor.cpp   -o md2610/direct_fourier_transform_parfor
md2610/direct_fourier_transform_parfor.cpp:1:33: fatal error: fourier_transform.hpp: No such file or directory
 #include "fourier_transform.hpp"
                                 ^
compilation terminated.
make: *** [md2610/direct_fourier_transform_parfor] Error 1

As before. Attempting to add the library path using both "export" and "ldconfig" hasn't solved the problem. The only solution I've found is to put a copy of the hpp file into the md2610 folder, but then there are further errors to do with this file I haven't seen before, so I'm guessing that's not a good idea.
Anyone got any thoughts? Is working in the network drive (homedir) an issue?

**Comment by mattdouthwaite** [comment]
Ok I think I've solved this by using the -I (uppercase i) flag with g++:

g++ -I /home/md2610/homedir/GitHub/hpce-2015-cw3/include/ direct_fourier_transform_parfor.cpp

Now get the same errors as mentioned earlier when I placed the .hpp file into the same folder, so I guess that's progress.

**Comment by ia2314** [comment]
Did you solve this? I get the same issue
