### ISSUE TITLE
Issue with chunked parallel_for

### ISSUE THREAD

**Issue by raymond-williams** [HPCE/hpce-2015-cw3#7]
The spec gives the following example for describing a chunked iteration space:

    tbb::parallel_for(tbb::blocked_range<unsigned>(i,j,K), const blocked_range<int> &chunk){
        for(unsigned i=chunk.begin(); i!=chunk.end(); i++ ){
            y[i]=myLoop(i);
        }
    }, tbb::simple_partitioner());

When applying this syntax to the direct Fourier transform I cannot get it to compile. The closest working implementation I've found is with a lambda function.

Note that I have not tried to compile the following example, but based on my working chunked direct Fourier transform implementation, I think this modification to the earlier example should work:

    tbb::parallel_for(tbb::blocked_range<unsigned>(i,j,K), [&](const tbb::blocked_range<unsigned> &chunk){
        for(unsigned i=chunk.begin(); i!=chunk.end(); i++ ){
            y[i]=myLoop(i);
        }
    }, tbb::simple_partitioner());

Please could you check which one is correct? I may just be doing something silly when trying to implement the original example. The unpacked example just below in the instructions works fine when applied to the direct Fourier transform by the way.

Also, please could you clarify if the data type of the iteration space is important? The example seems to be inconsistent between `unsigned` and `int`. Should we be using `size_t` for the direct Fourier transform since that is the type used in the unmodified original?

Thanks!

**Comment by m8pple** [comment]
You're right, the example given doesn't compile, it is missing the lambda part. Your
modification is correct. The unpacked version below it is correct (I think).

Thanks - not sure how no-one picked that up last year. I'll adjust as suggested.

**Comment by m8pple** [comment]
Oh, and you're also right on the unsigned versus size_t thing. I should have been using the
same thing everywhere, as in principle you could have sizeof(size_t)==8 so you could do
an FFT on 2^32 elements, but it would fail if sizeof(unsigned)==4.
